### ISSUE TITLE
Feature Suggestion: Relations Tab

### ISSUE THREAD

**Issue by ZeldasWetDream** [comp500/Curseforge-Userscripts#15]
Could we get an addition that when going to the relations tab it auto sorts to Dependents sub-sorted by Required Dependency such as the image below. It will make finding compatible and dependent mods easier.

![image](https://user-images.githubusercontent.com/64482973/131602666-5d19dba2-e4a9-455f-88e8-b5116260cf0b.png)

**Comment by unilock** [comment]
Would it be possible to automatically set the "Dependency Type" to "Required Dependency" for the *"Dependents"*  menu as well?

<img width="188" alt="image" src="https://github.com/comp500/Curseforge-Userscripts/assets/11802133/e3a69153-77c9-4bc1-9739-c12e6faaeb4d">

Currently, it gets reset to "All Types" whenever it's selected from the above dropdown.

**Comment by comp500** [comment]
@unilock Yeah, that can be done easily enough :)
