### ISSUE TITLE
Add redirect to legacy.curseforge.com 

### ISSUE THREAD

**Issue by alexeik** [comp500/Curseforge-Userscripts#23]
Add redirect to legacy.curseforge.com  with valid url.
Please

**Comment by comp500** [comment]
I'm guessing that CurseForge will remove the legacy site fairly soon, and I'm not really maintaining these userscripts much anymore, so I probably won't implement this.

**Comment by alexeik** [comment]
wait.. i mean Curseforge QOL Fixes script.
not that.
Curseforge QOL Fixes links forward to this project... error

**Comment by comp500** [comment]
This repository does contain the CurseForge QOL fixes script, if that's what you mean? Not sure what error you're referring to.

**Comment by alexeik** [comment]
yes it doesnt :)
but why?
https://greasyfork.org/en/scripts/389255-curseforge-qol-fixes 
links on that page routes here

**Comment by comp500** [comment]
...that is a correct link to this repository? The CurseForge QoL fixes script is in this project.
